### ISSUE TITLE
Fade out an effect

### ISSUE THREAD

**Issue by dmrickey** [kandashi/Custom-Token-Animations#18]
One of the things I've wanted to do with TMFX is to be able to update an existing animation so that I can remove it but have fade out instead of abruptly kill the effect.

Without having a custom effect, any updates to the token's FX restart the animation so depending on which effect I'm using it's super hard to just fade it out when removing it.

Example use case - add a blood effect but fade out on removal instead of just going abruptly from "bloody" to "normal".

All the above is from the perspective of using TMFX, and I've talked to a lot of people about trying to figure out a good way to accomplish this. I know this isn't supposed to replace TMFX, but if you could include a way to "kill" an animation by fading it out that would be awesome.

**Comment by kandashi** [comment]
Avalidable in 0.1.12
