### ISSUE TITLE
Adding two animations at once results in error at time of remove (addAnimation is not async)

### ISSUE THREAD

**Issue by napolitanod** [kandashi/Custom-Token-Animations#39]
I'm using Custom Token Animations with DAE firing and ItemMacro. I can get the animations on the token great. When the removeAnimByName fires I get an error for id being undefined. I have a console log in the script and have confirmed that a token object is being passed into the functions. Here is what I have for the snippet 
if(args[0]==="off"){
    console.log(myToken);
    await CTA.removeAnimByName(myToken, "extraFire", false, true);
    await CTA.removeAnimByName(myToken, "auraFire", false, true);
}

this is what the add function looks like to show that the names match  
if(args[0]==="on"){
    await CTA.addAnimation(myToken,extraFireData,false,"extraFire", false); 
    await CTA.addAnimation(myToken,auraData,false,"auraFire", false);
}

**Comment by kandashi** [comment]
Ive strengthened the logic behind adding/removing multiple animations. the textureData and name paths can now accept arrays to create/delete multiple at once
