### ISSUE TITLE
BUG: Render Underneath Token does not work

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Custom-Token-Animations#41]
EDIT: Okay after much experimentation, I've discovered that checking "Render Underneath Token" is permanently broken if you ever also apply "Permanent on Actor" and "Apply as Equipment" at the same time. Render Underneath Token only works if you never apply those other two.

**Comment by kandashi** [comment]
Hum , I can kinda understand why the Equipment one fails, but not the Actor one.. Ill investigate

**Comment by GambetTV** [comment]
The Actor One might not do that exactly. From what I can tell once you engage the Actor one once, you cannot undo it, and it might force some of the other settings to stick too.

**Comment by kandashi** [comment]
After reviewing this further I cannot make apply as equipment and render under token work nicely together
