### ISSUE TITLE
The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0

### ISSUE THREAD

**Issue by thatlonelybugbear** [kandashi/Custom-Token-Animations#48]
When I move a token around the map the following warning keeps poppin up in the console.

![image](https://user-images.githubusercontent.com/7237090/121903911-ab35a800-cd20-11eb-90d4-c23f545d97b5.png)

There are 5 instances of the token._id in the CTA.js.

Might need to change them to just .id at some point?

**Comment by kandashi** [comment]
I believe this was fixed
