### ISSUE TITLE
Image changes size if used on another token of different size

### ISSUE THREAD

**Issue by RicoTheBold** [kandashi/Custom-Token-Animations#49]
I'm attempting to apply an overlay on tokens (a frame that indicates how dangerous the monster is). If I apply the same image to another token that is a different size, the existing image(s) on the previous token(s) will change sizes to match (larger or smaller, depending on the relative size of the most recent token to get the image). Naming the effect a different name doesn't change the outcome as long as it's the same image.  This doesn't happen if it is applied as equipment, but that doesn't appear to currently work in Foundy 0.8.x. It also happens if I'm applying via the API using a macro or configuring it through the GUI options.

Verified currently with Foundry 0.8.7, Pathfinder 2 as the system (currently 2.4.0), and only Custom Token Animations 0.2.51 and socketlib 1.0.7 loaded. Had the issue with earlier versions in Foundry 0.7.x, but the equipment option was my workaround

In the below images, the claw overlay was applied to three tokens of different sizes, set as a static image with a scale of 1 (and different animation effect names for all 3). In the first image, the largest token was the most recently applied.  In the second image, I opened the existing effect on the smallest token using the "update" button, hit "create" to save without making any changes, and slightly panned the canvas to trigger the updated render.
![image](https://user-images.githubusercontent.com/42160122/122652621-fffc6880-d0fc-11eb-87dc-18fed52d33b7.png)
![image](https://user-images.githubusercontent.com/42160122/122652655-1c98a080-d0fd-11eb-8d35-7001570c971f.png)

**Comment by kandashi** [comment]
Ahh shoot yes. I ran into this with Next Up too. There is a fix, but it might not be for a few days im afriad

**Comment by kandashi** [comment]
seems to be fixed in the latest versions

**Comment by RicoTheBold** [comment]
Any chance these latest versions could be pushed to release? 0.2.51 is still the released version.

**Comment by kandashi** [comment]
pushed now
