### ISSUE TITLE
Feature Request: Allow players access to this module

### ISSUE THREAD

**Issue by Bryn1701** [kandashi/Custom-Token-Animations#51]
Greetings! First off what a fantastic module. I have been waiting for something like this for awhile, other modules touch on some of this modules abilities but no where near as good. As the title suggestions, I don't always have time to set up everyone's potential auras they might want. I have a player who has a lot of tokens they can summon, shape shifts etc being a Druid and would love to allow players the opportunity to use this module. I love how FX module has integrated this into the Permission Configuration(see screenshot below) and allowing certain players to have this permission, this would be perfect to allow some but not all players the ability to use this module. 

https://gyazo.com/b0df2e64134219cc5bdaea00f3e66abc

**Comment by kandashi** [comment]
I'll see what I can do about this
