### ISSUE TITLE
BUG: Issue with MidiQOL/Automated Animations when requiring a Saving Throw.

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Custom-Token-Animations#53]
I'm using Automated Animations and your module to create Auras that fire off when a Character Feature is being used. When this happens, a popup appears that has a single button on it, which says: "Remove CTA Effect." This works flawlessly except in the situation where the Feature you're using requires a Saving Throw. If that's the case, and you're using MidiQOL to automate Saving Throws, the Aura Fires off twice, and can't be removed, and the button window can't even be closed without refreshing Foundry. Disabling MidiQOL seems to fix the problem, as does removing the Saving Throw component of the item.

**Comment by kandashi** [comment]
This is not an issue with CTA, but with Automated Animations, best head over there
