### ISSUE TITLE
Add translate French

### ISSUE THREAD

**Issue by Elfenduil** [kandashi/Custom-Token-Animations#55]
Hi,

Can you add the translate to French, see file in Att

Thx
[Traduire CTA.docx](https://github.com/kandashi/Custom-Token-Animations/files/7302174/Traduire.CTA.docx)

**Comment by Elfenduil** [comment]
Upgrade
[Traduire CTA.docx](https://github.com/kandashi/Custom-Token-Animations/files/7594838/Traduire.CTA.docx)

**Comment by Knackie** [comment]
https://github.com/kandashi/Custom-Token-Animations/pull/56
