### ISSUE TITLE
Update doesn't recall prior setting of "Number of Copies"

### ISSUE THREAD

**Issue by dstein766** [kandashi/Custom-Token-Animations#7]
FVTT 0.7.9
DND5E 1.2.4
CTA 0.1.04

When Updating a pre-existing CTA configuration, the data form doesn't populate the Number of Copies field with the previously configured value, so an effect initially created with multiple copies (like a rotating Ioun Stone halo with multiple instances of the stone graphic) has to have the # of copies manually re-specified during the editing process.

**Comment by kandashi** [comment]
closes with #9
